export const TESTING_RECOGNIZED_DELEGATE_COUNT = 1;

export const TESTING_SHADOW_DELEGATE_COUNT = 1;

export const TESTING_TOTAL_DELEGATE_COUNT = TESTING_RECOGNIZED_DELEGATE_COUNT + TESTING_SHADOW_DELEGATE_COUNT;

export const TESTING_MKR_DELEGATED_AMOUNT = 0;
