// number of active polls in test db
export const TESTING_ACTIVE_POLLS_COUNT = 2;
export const TESTING_ENDED_POLLS_COUNT = 1;
export const TESTING_TOTAL_POLLS_COUNT = TESTING_ACTIVE_POLLS_COUNT + TESTING_ENDED_POLLS_COUNT;
